appName=Khoirunnasyien
institutionName=Khoirunnasyien
applicationId=com.khoirunnasyien.tahfiz
defaultVersionName=1.5.1
defaultVersionCode=13
firebaseProjectId=khoirun-app
dartEntryPoint=lib/main_khoirunnasyien.dart
authEmailDomain=khoirunnasyien.app
paymentBankName=BSI
paymentAccountNumber=7117245448
paymentAccountHolder=Fahmi Ramdani
