name: khoirunnasyien
description: "Tahfiz App Project"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # Core
  go_router: ^17.0.1
  get_it: ^9.2.0
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  dart_either: ^2.0.0
  
  # UI
  skeletonizer: ^2.1.2
  image_picker: ^1.2.1
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1

  # Firebase
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_storage: ^13.0.6
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  timeago: ^3.7.1
  equatable: ^2.0.8
  flutter_image_compress: ^2.4.0
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Railey
      fonts:
        - asset: assets/fonts/Railey.ttf