org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# Plugin Flutter tersimpan di drive C:, sedangkan workspace di drive D:.
# Incremental cache Kotlin tidak mendukung source/base dari root berbeda.
kotlin.incremental=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
